server:
  port: 8081

spring:
  datasource:
    password: admin
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/payment_service_db
    username: postgres

  application:
    name: PAYMENT-SERVICE

  config:
    import: configserver:http://localhost:9296

  jpa:
    hibernate:
      ddl-auto: update